#!/bin/bash

set -e

# Helper for searching code base without searching through external code

cd "$(git rev-parse --show-toplevel)"

exec ack "$@" \
    --ignore-directory .tox \
    --ignore-directory .mypy_cache \
    --ignore-directory .dmypy.json \
    --ignore-directory dist \
    --ignore-directory build \
    --ignore-directory "*.egg-info" \
    --ignore-directory tools
