---

name: Lint

on:
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install venv
        run: ./tools/uv sync --extra tools --locked

      - name: Ensure linter is happy
        run: ./tools/ci lint

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install venv
        run: ./tools/uv sync --extra tools --locked

      - name: Ensure mypy is happy
        run: ./tools/ci types

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install venv
        run: ./tools/uv sync --extra tools --locked

      - name: Ensure code is formatted
        run: |
          ./tools/ci format

          git status --porcelain

          # Complain if there were changes
          if [[ ! -z "$(git status --porcelain)" ]]; then
            echo "=========================================="
            echo "Found changes!"
            echo "Please run ./format before committing code"
            echo "=========================================="
            git diff
            exit 1
          fi
